### PR TITLE
A few changes to the catching the errors.

### PR DESCRIPTION
**Pull request by rwblair**
Awesome work on the PR. I tried to tighten the catches up to be closer to the calls out to the hed-validator. Also made it use Issue objects errorToIssue function for pretty printing the error call stack.

One thing I'm not sure about is emitting an error or warning. I switched it to emit a warning so that datasets would still upload to openneuro and other apps that need no errors to proceed. I've gone back and forth on this, let me know what you think.

### CODE REVIEW

**Comment by rwblair** [comment]
Should approve me to run the workflows, I've got lost of tests failing locally that I'm trying to fix, be nice to see them fail in CircleCI.

**Comment by happy5214** [comment]
> Should approve me to run the workflows, I've got lost of tests failing locally that I'm trying to fix, be nice to see them fail in CircleCI.

@rwblair I approved you, but the CircleCI tests didn't run, just the test-bids-examples GitHub action.

**Comment by rwblair** [comment]
Got the number failing down to 7, with 2 of which match the 2 that are failing in main PR. 

Things like code mismatches expecting 205 but getting 116. ~Would that happen if I was running the latest hed-validator?~ that was silly to ask, tested with 2.0.4 and had a lot more failures. Testing with 3.0.6 reduced failing tests to only 4, still getting 116 instead of 205.

And finally using 3.0.5 matches your PR. Should of paid more attention to the lock file.

**Comment by rwblair** [comment]
2ce8f94 should fix the issues we see being thrown by circle.

**Comment by happy5214** [comment]
I'm bumping the dependency version to 3.1.1 in this PR, so I'll have to fix the codes. I'll do that once this side PR is merged. Do I commit the modified lock file or do you handle that?

**Comment by rwblair** [comment]
I didn't push any changes to the lock file.

I'm okay with failing hed tests getting merged since well be doing #1299 next which will hopefully straighten all this out.

If you are ok with the changes in this PR, once you merge it into  happy5214/reorder-hed-execution I'll go ahead and merge bids-standard/bids-validator/pull/1298

**Comment by happy5214** [comment]
Well, I mean who will fix the lock file? Will it be done automatically, or who is responsible for committing the change to 3.1.1? I only changed the package.json in the PR.

**Comment by rwblair** [comment]
Gotcha, I went ahead and committed mine. It isn't done automatically unfortunately.

**Pull request merged**
